[package]
name = "evdev-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "0.12"
signal-hook = "0.3"
notify-rust = "4"
users = "0.11"
crossbeam-channel="0.5"
